"""initial AthleteGuard schema"""
from alembic import op
import sqlalchemy as sa

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('users', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(120), nullable=False), sa.Column('email', sa.String(255), nullable=False, unique=True), sa.Column('password_hash', sa.String(255), nullable=False), sa.Column('role', sa.String(20), nullable=False, server_default='athlete'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index('ix_users_email', 'users', ['email'])
    op.create_table('athletes', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False, unique=True), sa.Column('sport', sa.String(80), nullable=False), sa.Column('position', sa.String(80)), sa.Column('age', sa.Integer()), sa.Column('height', sa.Float()), sa.Column('team', sa.String(120)), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index('ix_athletes_user_id', 'athletes', ['user_id']); op.create_index('ix_athletes_team', 'athletes', ['team'])
    op.create_table('workouts', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('athlete_id', sa.Integer(), sa.ForeignKey('athletes.id', ondelete='CASCADE'), nullable=False), sa.Column('exercise', sa.String(80), nullable=False), sa.Column('duration_minutes', sa.Integer(), nullable=False), sa.Column('intensity', sa.Integer(), nullable=False), sa.Column('repetitions', sa.Integer(), nullable=False), sa.Column('session_load', sa.Integer(), nullable=False), sa.Column('performance_score', sa.Integer()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index('ix_workouts_athlete_id', 'workouts', ['athlete_id'])
    op.create_table('recoveries', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('athlete_id', sa.Integer(), sa.ForeignKey('athletes.id', ondelete='CASCADE'), nullable=False), sa.Column('sleep_hours', sa.Float(), nullable=False), sa.Column('fatigue', sa.Integer(), nullable=False), sa.Column('soreness', sa.Integer(), nullable=False), sa.Column('stress', sa.Integer(), nullable=False), sa.Column('rest_days', sa.Integer(), nullable=False), sa.Column('training_intensity', sa.Integer(), nullable=False), sa.Column('recovery_score', sa.Integer(), nullable=False), sa.Column('recovery_status', sa.String(20), nullable=False), sa.Column('breakdown', sa.String(1000), nullable=False, server_default='{}'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index('ix_recoveries_athlete_id', 'recoveries', ['athlete_id'])
    op.create_table('movement_analyses', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('athlete_id', sa.Integer(), sa.ForeignKey('athletes.id', ondelete='CASCADE'), nullable=False), sa.Column('workout_id', sa.Integer(), sa.ForeignKey('workouts.id', ondelete='SET NULL')), sa.Column('exercise', sa.String(80), nullable=False), sa.Column('repetitions', sa.Integer(), nullable=False), sa.Column('depth_score', sa.Integer(), nullable=False), sa.Column('knee_alignment_score', sa.Integer(), nullable=False), sa.Column('stability_score', sa.Integer(), nullable=False), sa.Column('consistency_score', sa.Integer(), nullable=False), sa.Column('movement_quality_score', sa.Integer(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index('ix_movement_analyses_athlete_id', 'movement_analyses', ['athlete_id'])
    op.create_table('risk_assessments', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('athlete_id', sa.Integer(), sa.ForeignKey('athletes.id', ondelete='CASCADE'), nullable=False), sa.Column('movement_quality', sa.Integer(), nullable=False), sa.Column('recovery_score', sa.Integer(), nullable=False), sa.Column('training_load', sa.Integer(), nullable=False), sa.Column('workload_change_percentage', sa.Float(), nullable=False), sa.Column('risk_level', sa.String(20), nullable=False), sa.Column('reasons', sa.String(2000), nullable=False, server_default='[]'), sa.Column('recommendation', sa.String(500), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False)); op.create_index('ix_risk_assessments_athlete_id', 'risk_assessments', ['athlete_id'])

def downgrade():
    op.drop_table('risk_assessments'); op.drop_table('movement_analyses'); op.drop_table('recoveries'); op.drop_table('workouts'); op.drop_table('athletes'); op.drop_table('users')
